### ISSUE TITLE
OpenSSL installation

### ISSUE THREAD

**Issue by Kolcha** [miurahr/aqtinstall#155]
since some 5.12.x Qt is built against OpenSSL 1.1.x (on Windows and Linux), and installer has an option to install this OpenSSL version. this is very convenient to have it, because if Qt app establish HTTPS connections through QtNetwork OpenSSL runtime is required and you have to build the compatible version by yourself...

it would be nice to have an option to install it with Qt.

consider next scenarios in [GitHub Actions](https://github.com/jurplel/install-qt-action) (especially for Windows builds):
- run tests which establish HTTPS connections
- create some build artifacts (aka nightly builds)

**Comment by miurahr** [comment]
aqt tool windows tools_openssl 1.1.1-1 qt.tools.openssl.win_x64

**Comment by tamlok** [comment]
Hi,

Where could we find it after install?

https://pipelines.actions.githubusercontent.com/VAnhysSj0CGWFjoioxVs0fy68pCYUxN5sbjZZlC4i8kZuupQgT/_apis/pipelines/1/runs/76/signedlogcontent/4?urlExpires=2020-11-30T13%3A18%3A08.7424558Z&urlSigningMethod=HMACV1&urlSignature=P4%2B3Q8HH090tqQpRAk%2BIy4cpibxJAjuC1%2BDxCdNIl5Y%3D

**Comment by tamlok** [comment]
Maybe should escape the slash in the output directory:

```
python -m aqt tool windows tools_openssl_x64 1.1.1-1 qt.tools.openssl.win_x64 -O D:\a\vnote/Qt
```

**Comment by tamlok** [comment]
Got it. The version should be `1.1.1-4` now.

**Comment by miurahr** [comment]
We need to improve `aqt tool` subcommand to find automatically proper version....

**Comment by tamlok** [comment]
It is strange that the Qt 5.12.10 installed by aqtinstall is built with openssl 1.1.1g while the QtTools installed is openssl 1.1.1d.

**Comment by miurahr** [comment]
Tools repository for Linux is here. We can find 1.1.1d.
https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_openssl_x64/qt.tools.openssl.gcc_64/

aqt refer the metadata database here.
https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/tools_openssl_x64/Updates.xml

These are independent directory from Qt versions, and last updated in 24, Aug.

Qt 5.12.10 metadata database is 
https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_51210/Updates.xml
which is updated in 09, Nov.

It seems expected behavior because these two versions are defined on Qt download site.

**Comment by tamlok** [comment]
Got it. But we need to download 1.1.1g to make the built app work on windows, right?

**Comment by miurahr** [comment]
It is pretty out of scope for the installation utility.

Openssl 1.1.1d and 1.1.1g have [same ABI](https://wiki.openssl.org/index.php/ABI_Tracker) and share the same SO name (1.1), and difference is just patch level (d or g).

off-topic:
OpenSSL project plans to release 3.0.0 in this year,  that will break a compatibility with 1.1.x.

**Comment by tamlok** [comment]
Just tried it and 1.1.1g couldnot work with 1.1.1d. I just copy.1.1.1g from other places to package with. Thanks!
