### ISSUE TITLE
Quick question regarding Qt 5.10

### ISSUE THREAD

**Issue by LorenzE** [miurahr/aqtinstall#190]
How is it possible to install Qt 5.10 with aqt when it is not possible with the official Qt installer? I was not able to find teh pre-built binaries for Qt 5.10 in the Qt download archives. Just wondering ... :)

**Comment by miurahr** [comment]
You can specify  "5.10.0" or "5.10.1" as version.

**Comment by miurahr** [comment]
You can not install versions which the Qt foundation had already deprecated  binary packagea on download site.
aqt looks https://download.qt.io/ when vresion specified, where is managed by the Qt Foundation.

**Comment by miurahr** [comment]
Qt 5.10.1 binaries are still existing at https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5101/ so you may be able to install it with aqt.

If you are willing to install the version, which has already removed at download archive, [The internet archive project](https://www.archive.org) may help you,  but  aqtinstall tool does not support it (Because you can specify a mirror site as a command line. .you can put URL of the internet archive theoretically, but it will fails with connection timeout or it is considered as an abuse of the internet archive.)

It would be  a good idea for you to make a mirror of download site, if you have a plan to stick older Qt versions. The Qt Foundation can remove binary packages which has already been an end-of-life in anytime.
aqt can install Qt library from your mirror site using an option: `-b <mirror_url>`

eg. Qt5.3 https://web.archive.org/web/20200221064247/http://download.qt.io/online/qtsdkrepository/linux_x64/
desktop/qt5_53/
