### ISSUE TITLE
Download link for older Qt versions dissapeared from qt.io

### ISSUE THREAD

**Issue by EtlamGit** [miurahr/aqtinstall#216]
I tried to install older Qt version (5.5). This worked well some month ago.

But now I get an error message:
```
python3 -m aqt install 5.5 linux desktop -O /home/runner/work/minutor/Qt
2021-02-12 19:08:10,415 - aqt - INFO - aqtinstall(aqt) v0.11.1 on Python 3.9.1 [CPython GCC 5.5.0 20171010]
2021-02-12 19:08:10,981 - aqt - ERROR - Download error when access to https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_55/Updates.xml
Server response code: 404, reason: Not Found
Error: The process 'python3' failed with exit code 1
```
indicating that the download link is not valid anymore.
When looking at that server directory, it seems that all version prior 5.9 are removed now.

**Comment by EtlamGit** [comment]
I think this issue is still valid.

What is our plan with older Qt versions when the download links are removed by qt.io company?

**Comment by vadi2** [comment]
What should it be? Unsupported versions by Qt are removed, I don't think it should be this actions' job to maintain insecure Qt versions by itself.

**Comment by EtlamGit** [comment]
If you wait some more time, all versions of Qt will be "Unsupported". The new license model implies that access to the free sources will be removed completely in the future. It would be good to have a plan B before that.

We can wait for a Qt fork that provides links to older releases. Or just mirror that old files ourself. Yes you are right it is ridiculous to maintain such a mirror for a project like this. But if nobody is doing it, access to the Qt installers will be gone soon. That would also be the end of this project.

**Comment by unitedtimur** [comment]
We need too use qt 5.5, what about this? Qt has mirror for archives https://download.qt.io/new_archive/qt/5.5/5.5.1/

**Comment by pzhlkj6612** [comment]
Hi @unitedtimur . 

> We need too use qt 5.5, what about this? Qt has mirror for archives https://download.qt.io/new_archive/qt/5.5/5.5.1/

Thank you for providing the link.
However, aqtinstall cannot handle it. https://download.qt.io/new_archive/qt/5.5/5.5.1/ contains offline Qt installers and source code of Qt, but no pre-compiled binary files (dynamic libraries, utilities, etc.) like the ones in https://download.qt.io/online/qtsdkrepository/ .

Please note that aqtinstall is essentially a tool that helps you download, extract and configure files from https://download.qt.io/online/qtsdkrepository/ . It is not able to invoke Qt installer or compile anything.

**Comment by miurahr** [comment]
@unitedtimur When you are interested in implementing and maintain the feature, you are welcome raising pull-request. 
A past attempt #251 was abandoned, because there is not enough contribution for the feature to handle offline installer.

There are several criteria to add the feature.

1. it should be maintained by author(s) like you. A motivation to start `aqtinstall` is to **avoid** offline installer by several reasons. That's why I don't want to maintain it.
2. it should support all versions, not only a specific version.
3. there should be tests in CI/CD environment
4. it should work on all the platform which Qt supports.
5. it should run well on headless environment (optional)
6. it should be well documented.

@unitedtimur when you want to install only a specific old version, such as 5.5.1, you can just use an offline installer with genuine scripting function of QtIFW. https://doc-snapshots.qt.io/qtifw-master/noninteractive.html
It will be significantly easier  than implementing generalize scripts for all the old qt versions on all the platforms.

**Comment by pzhlkj6612** [comment]
> <a>3.</a> there should be tests in CI/CD environment
> <a>5.</a> it should run well on headless environment (optional)

Well, I think CI/CD is headless environment too, thus no optional, but required.

**Comment by miurahr** [comment]
> > 3. there should be tests in CI/CD environment
> > 5. it should run well on headless environment (optional)
> 
> Well, I think CI/CD is headless environment too, thus no optional, but required.

Thank you for showing an important aspect of an offline installer.
The genuine scripting feature is to automate a GUI operation, such as enter some text into form then click OK button. 

GUI support may be mandatory in my understanding because test cases in #251 are failed because some environments on Github actions is headless. 

Maintainer for the feature may need to setup CI/CD environment with GUI support for Windows, macOS and Linux. It will be hard work and requires running cost.

**Comment by miurahr** [comment]
Related #236
