### ISSUE TITLE
Consideration on command line interface

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#306]
There are many variation of command line arguments now. It is good time to rethink a design. 

for examples,

```
aqt install --outputdir /opt/Qt 5.12.0 linux desktop -m qtcharts qtnetworkauth
aqt install 5.15.2 linux android android_armv7
aqt install 5.15.0 linux desktop wasm_32

aqt examples 5.15.2 windows desktop -m qtcharts qtnetworkauth
aqt doc 5.15.2 windows desktop -m qtcharts qtnetworkauth
aqt src 5.15.2 windows desktop --archives qtbase --kde

aqt list qt5 linux desktop
aqt list qt6 mac desktop
aqt list qt6 mac desktop --modules latest
aqt list qt6 windows desktop --arch 6.1.2
aqt list tools windows desktop 
aqt list tools linux desktop --tool tools_ifw 
```

#299 introduces following cli

```
aqt tool windows desktop tools_openssl_x64
aqt tool windows android tools_qt3dstudio_runtime_240
aqt tool linux desktop tools_ifw
aqt tool mac desktop tools_ninja
```

If there is more consistency, in words such as `tools` and `tool` and common order of arguments, it would be better.

**Comment by ddalcino** [comment]
We could set the first two positional arguments of each command to be `<host> <target>`. That would turn the example list into:

```
aqt install linux desktop --outputdir /opt/Qt 5.12.0 -m qtcharts qtnetworkauth
aqt install linux android 5.15.2 android_armv7
aqt install linux desktop 5.15.0 wasm_32

aqt examples windows desktop 5.15.2 -m qtcharts qtnetworkauth
aqt doc windows desktop 5.15.2 -m qtcharts qtnetworkauth
aqt src windows desktop 5.15.2 --archives qtbase --kde

aqt list linux desktop qt5
aqt list mac desktop qt6
aqt list mac desktop qt6 --modules latest
aqt list windows desktop qt6 --arch 6.1.2
aqt list windows desktop tools
aqt list linux desktop tools --tool tools_ifw 

aqt tool windows desktop tools_openssl_x64
aqt tool windows android tools_qt3dstudio_runtime_240
aqt tool linux desktop tools_ifw
aqt tool mac desktop tools_ninja

```

**Comment by ddalcino** [comment]
Additionally, I think the syntax of `aqt list` needs some work. Consider these commands:

```bash
aqt list linux desktop tools                          # list all tools for linux desktop
aqt list linux desktop tools --tool tools_ifw         # list all tool variants for ifw
aqt list linux desktop tools --tool-long tools_ifw    # long listing of all tool variants for ifw
```

You have to type the word 'tool' three times in a row to get anything done. I used '--tool' and '--tool-long' for the options because I wanted to make it clear that these options would only work when 'category' is 'tools'; I can't think of a better way to do that.

I think that `aqt list qt` and `aqt list tools` should be two different subcommands. They do similar things, but they cannot accept the same flags. If they were turned into separate subcommands, the flags would all make a lot more sense to a new user.

This is the syntax I would prefer:

```bash
aqt list-tool linux desktop               # list all tools for linux desktop
aqt list-tool linux desktop tools_ifw     # list all tool variants for ifw
aqt list-tool linux desktop ifw           # list all tool variants for ifw ('tools_' prefix is optional)
aqt list-tool linux desktop -l tools_ifw  # long listing of all tool variants for ifw
aqt list-tool linux desktop -l ifw        # long listing of all tool variants for ifw

aqt list-qt linux desktop                              # list versions of qt
aqt list-qt mac                                        # print all targets for Mac OS
aqt list-qt mac desktop                                # print all versions of Qt 
aqt list-qt mac desktop --spec ">=5.13.0,<6.0"         # print all versions of Qt between 5.13.0 and 6
aqt list-qt mac desktop --extension wasm               # print all wasm versions of Qt
aqt list-qt mac desktop --spec "5.9"                   # print all versions of Qt 5.9
aqt list-qt mac desktop --spec "5.9" --latest-version  # print latest Qt 5.9
aqt list-qt mac desktop --modules 5.12.0               # print modules for 5.12.0
aqt list-qt mac desktop --spec "5.9" --modules latest  # print modules for latest 5.9
aqt list-qt mac desktop --extensions 5.9.0             # print choices for --extension flag
aqt list-qt mac desktop --arch 5.9.9                   # print architectures for 5.9.9/mac/desktop
aqt list-qt mac desktop --spec "5" --arch latest       # print architectures for the latest Qt 5

```

This solution lets `argparse` figure out which flags will work with each command. With this change, the `--filter-minor` flag would need to be replaced with a flag that takes receives a SimpleSpec, since we have lost the Qt major version we were reading from the 'category' parameter. I expect that it would be relatively easy to make this change and it would result in simpler code.

**Comment by miurahr** [comment]
An idea to use `list-tool` and `list-qt`, and utilize SimpleSpec as an argument  looks good direction to me.
We can align other sub commands to change as similar as the syntax.

```
aqt install-tool linux desktop openssl_x64
aqt install-doc linux desktop 5.12.1 --outputdir /opt/Qt
aqt install-example windows desktop 6.1.0
aqt install-qt mac desktop 6.0.0  --modules qtcharts
aqt install-qt windows desktop --spec "6.0" --arch msvc2019_x64
```

We can keep `aqt install 5.12.1 linux desktop` syntax for backward compatibility, that don't surprise  users.

**Comment by ddalcino** [comment]
> We can keep `aqt install 5.12.1 linux desktop` syntax for backward compatibility, that don't surprise users.

That's a really good point. So, the full list of subcommands would be:

```
aqt install-tool
aqt install-doc
aqt install-example
aqt install-src
aqt install-qt

aqt list-tool
aqt list-qt

aqt install
aqt tool
aqt doc
aqt example
aqt src
```

Would we mark `aqt (install|tool|doc|src)` as deprecated in the documentation/program output/help text?

**Comment by miurahr** [comment]
> Would we mark aqt (install|tool|doc|src) as deprecated in the documentation/program output/help text?

Yes, we can show warning message after showing aqt version line in stderr.

**Comment by ddalcino** [comment]
Ok, since #354 and #355 were merged, I think the only part of this issue that has not yet been addressed is this feature:

> ```
> aqt install-qt windows desktop --spec "6.0" --arch msvc2019_x64
> ```

I think that this feature could be very useful, particularly if you're trying to install an LTS release like 5.12, which is still receiving new patch updates after 3 years.

Are there any other parts of this issue that have not yet been addressed?

**Comment by miurahr** [comment]
> Are there any other parts of this issue that have not yet been addressed?

I have no idea what to be added.
There are already many suggestions through improvement of documentations.
 
It would be enough to release v2.0.0,  and I'd like to work for further improvement such as `aqt install-qt windows desktop --spec "6.0" --arch msvc2019_x64` on v2.1 development.

**Comment by ddalcino** [comment]
> It would be enough to release v2.0.0, and I'd like to work for further improvement such as `aqt install-qt windows desktop --spec "6.0" --arch msvc2019_x64` on v2.1 development.

That's probably a good idea. I imagine that it would be easy to add code like this to `aqt.installer.Cli.run_install_qt` and `_run_src_doc_examples`:

```python
qt_version = args.qt_version
if qt_version is None:
    qt_version = MetadataFactory(..., spec=SimpleSpec(args.spec)).getList().latest()
```

This would work for the easy cases, but there are a lot of edge cases to account for, and nailing them all down might be a lot of work. Here are a few that I can think of off the top of my head:

* For Qt 6+, on Android, if you don't pass an extension to the MetadataFactory, asking for a list of versions will fail. If you're using a spec like "*", or ">=5.12,<6.5", it could be very difficult to figure out if you need to pass an extension to MetadataFactory at all. I suppose you could use a trial-and-error approach.
* For the `wasm_32` architecture, you would need to pass the `wasm` extension to MetadataFactory.

I'm sure that there are other edge cases that I'm missing.

Also, I think it would be helpful for `aqt install-qt --spec` to write to `logger.info` a note about which version of Qt it is actually installing. If you ask for `--spec  "*"`, you might be very surprised when it installs some version of Qt 5 and not Qt 6 if you don't tell it what Android architecture you want.

**Comment by ddalcino** [comment]
Suggestion regarding new `install-qt/src/doc/example` syntax: let's turn the `qt_version` parameter into `qt_version_or_spec`.

The current proposed interface (https://github.com/miurahr/aqtinstall/issues/306#issuecomment-878667850) looks like this:
```bash
aqt install-qt windows desktop 6.0.4 msvc2019_x64                  # install Qt 6.0.4 for 64-bit msvc2019
aqt install-qt windows desktop --spec "6.0" --arch msvc2019_x64    # install Qt 6.0.4 for 64-bit msvc2019
```
In the first example, `qt_version` and `arch` are both optional positional arguments. In the second example, `qt_version` has been omitted, which means that the `--spec` option is now required. You cannot specify the architecture as a positional argument, because it would wind up in the `qt_version` position.

This interface is probably OK, but I think it's unnecessarily hard to implement, explain, and type.

This is the interface I would prefer:

```bash
aqt install-qt windows desktop 6.0.4 msvc2019_x64      # install Qt 6.0.4 for 64-bit msvc2019
aqt install-qt windows desktop 6.0 msvc2019_x64        # install Qt 6.0.4 for 64-bit msvc2019
aqt install-qt windows desktop "<6.1" msvc2019_x64     # install Qt 6.0.4 for 64-bit msvc2019
aqt install-qt windows desktop ">1,<6.1" msvc2019_x64  # install Qt 6.0.4 for 64-bit msvc2019
```

I have a working implementation of this interface at #392 already. I can modify my implementation to fit the earlier proposed interface, but it would be a little extra work. I would like to discuss changes to this interface before going any further.
