### ISSUE TITLE
How to install beta qt version

### ISSUE THREAD

**Issue by EndrII** [miurahr/aqtinstall#330]
How to install Qt 6.2 beta for android with all modules?

**Comment by ddalcino** [comment]
Are you trying to install the preview build of Qt 6.2.0? The full release of 6.2.0 was released two weeks ago; you might be better off using that one.

What have you tried so far?

**Comment by ddalcino** [comment]
Since #351 was merged, I think the tutorials at https://aqtinstall.readthedocs.io/en/latest/getting_started.html#installing-qt-for-android and https://aqtinstall.readthedocs.io/en/latest/getting_started.html#installing-modules should cover everything you need to install Qt 6.2.0 for android with all modules. If the tutorial was unclear, please let us know!

**Comment by EndrII** [comment]
@ddalcino O thanks you. it is looks useful
