### ISSUE TITLE
Qt 5.9 installation was broken at some point

### ISSUE THREAD

**Issue by jurplel** [miurahr/aqtinstall#363]
`aqt install 5.9 linux desktop` returns "Invalid version string: '5.9'"

Qt 5.9 has a weird package name but it is hosted: https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_59/

This worked in 1.1.3 but is broken in 1.2.x, as I discovered when trying to update the version.
https://github.com/jurplel/install-qt-action/runs/3303265869

**Comment by ddalcino** [comment]
You are correct; this is broken in the master branch as well. This happens because `aqt` is now using `semantic_version` for version comparisons, and 5.9 is not a valid semantic version.

For future reference, the proper way to install Qt 5.9 will be `aqt install-qt linux desktop 5.9.0` in version 2.0, or `aqt install 5.9.0 linux desktop` in the stable release. Unfortunately, neither of these commands work yet.

The metadata module had this problem, and it was fixed in #312; apparently the fix was never applied to the installer.

**Comment by ddalcino** [comment]
Does #364 work for you?

**Comment by jurplel** [comment]
Looks like it works

**Comment by jurplel** [comment]
Will there be a release to fix this bug?

**Comment by ddalcino** [comment]
I'm not sure when version 2.0 will be released, but I would expect it soon. According to https://github.com/miurahr/aqtinstall/issues/306#issuecomment-894603236, it looks like the last item that was planned for v2.0 will be pushed back to v2.1. 

If you want to update install-qt-action, I would recommend waiting for version 2.0. The new version makes it a lot easier to install tools, because you will not need to supply a version number or architecture for each tool.

If you can't wait that long, I opened #365 to help you out.

Thanks for all your hard work on install-qt-action, we really appreciate it!

**Comment by jurplel** [comment]
Okay, it should be no problem holding out a little longer. I was just updating it to resolve some issues on qt6 support. Appreciate the kind words, wouldn't be possible without this excellent piece of software.

**Comment by miurahr** [comment]
v1.2.5 out.

**Comment by jurplel** [comment]
Big thanks!
