### ISSUE TITLE
Feature: display list for specific Qt version and platform

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#37]
Current aqt has a command 'list' but it has  not been  implemented yet.
Here is an issue to watch implementation progress.

- [ ] add command argument to specify platform and version

- [ ] can download Update.xml

- [ ] can display all components which can install

- [ ] can display description for package

- [ ] can display dependencies

**Comment by EndrII** [comment]
Until this pool request is finished, you can tell me how to find out the name of the component I need
e.g. QtInstallerFramework and install it?

**Comment by EndrII** [comment]
Sorry, I already found a solution.
```
aqt tool linux tools_ifw 3.1.1 qt.tools.ifw.31
```

**Comment by EndrII** [comment]
it would also be nice to specify an output directory during installation or to separate packages by platform

The problem is that I need to install qif for 3 platforms (win linux and mac). Once installed, mac rewrites linux files.

This is qif after installing from all platforms. But there are no Linux files because they were installed first.
![image](https://user-images.githubusercontent.com/12465465/72705346-4cd8ba00-3b6c-11ea-8613-6012fb387142.png)

**Comment by miurahr** [comment]
RTM,  read the Readme, or -O,  and please don't high jack a ticket  by unrelated topic.
