### ISSUE TITLE
CI improvement for uploading test.pypi.org

### ISSUE THREAD

**Issue by miurahr** [miurahr/aqtinstall#409]
An uploading test of test.pypi.org is often failed when file has already  existed.
We run a test of uploading on push, but it is better to run manually now, because release procedure has been stable.

**Comment by pzhlkj6612** [comment]
> An uploading test of test.pypi.org is often failed when file has already existed.

I think I've found the reason. Fixes in #410 need to be reconsidered. I'll post my analysis later.

**Comment by pzhlkj6612** [comment]
Well, I think this is caused by the version number not being updated by [setuptools-scm](https://github.com/pypa/setuptools_scm) *in some cases*. When does setuptools-scm update the version number? Figuring this out may help us find the key cause of this problem.

I'm sorry that I found my speculation was wrong due to insufficient evidence, and now I don't have enough time to dig into this. I shouldn't block the release of v2.1, so I think you can ignore my comment and merge #410 .
