### ISSUE TITLE
Windows 10: Downloads wrong archive during installation

### ISSUE THREAD

**Issue by fdennis** [miurahr/aqtinstall#41]
Running latest master branch (v0.4.2) on windows 10.

**Steps to reproduce**
In powershell:
`python -m aqt install 5.12.4 windows desktop win64_msvc2017_64`

**Expected behavior**
Everything should be installed without any problems.

**Actual behavior**
Build fails, see 
[stack_trace.txt](https://github.com/miurahr/aqtinstall/files/3647544/stack_trace.txt)

I did some investigating regarding why this exception appears. It seems that a few of the .7z files are redirects. In retrieve_archive() in installer.py we allow for one redirect, however, in some cases the redirect is also a redirect.

I solved this by setting `allow_redirects=False` to True in `r = requests.get(url, stream=True, allow_redirects=False)`

Is there a reason why redirects are not allowed?

**Comment by miurahr** [comment]
There are some problematic mirror sites (especially in China), so I've disabled *automatic* redirection. Instead automatic one, I've handle it manually.
 
Checking blacklist before 
https://github.com/miurahr/aqtinstall/blob/master/aqt/installer.py#L67
`  r = requests.get(newurl, stream=True, allow_redirects=False)`
so It can be `  r = requests.get(newurl, stream=True, allow_redirects=True)`.

In some case in Asia continent, redirection in mirror which is not blacklist redirect to problematic one.
It is because I've disable it for debug purpose, and forget flip it for production.
 
Thank you for detailed investigation!
