### ISSUE TITLE
MemoryError during decompression & Unable to read c:\Users\qt\work\install\mkspecs\qconfig.pri

### ISSUE THREAD

**Issue by dwheeld** [miurahr/aqtinstall#416]
A recent install gave this bug report:

  File "C:/msys64/mingw64/lib/python3.9/site-packages/py7zr/py7zr.py", line 948, in extractall
    self._extract(path=path, return_dict=False, callback=callback)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/py7zr/py7zr.py", line 604, in _extract
    self.worker.extract(
  File "C:/msys64/mingw64/lib/python3.9/site-packages/py7zr/py7zr.py", line 1165, in extract
    self.extract_single(
  File "C:/msys64/mingw64/lib/python3.9/site-packages/py7zr/py7zr.py", line 1276, in extract_single
    raise e
  File "C:/msys64/mingw64/lib/python3.9/site-packages/py7zr/py7zr.py", line 1261, in extract_single
    crc32 = self.decompress(fp, f.folder, ofp, f.uncompressed, f.compressed, src_end)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/py7zr/py7zr.py", line 1313, in decompress
    tmp = decompressor.decompress(fp, out_remaining)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/py7zr/compressor.py", line 630, in decompress
    tmp = self._decompress(self._unused + data, max_length)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/py7zr/compressor.py", line 602, in _decompress
    data = decompressor.decompress(data)
MemoryError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.9/site-packages/aqt/installer.py", line 99, in run
    args.func(args)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/aqt/installer.py", line 294, in run_install_qt
    run_installer(qt_archives.get_packages(), base_dir, sevenzip, keep)
  File "C:/msys64/mingw64/lib/python3.9/site-packages/aqt/installer.py", line 835, in run_installer
    pool.starmap(installer, tasks)
  File "C:/msys64/mingw64/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:/msys64/mingw64/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
MemoryError
Arguments: `['C:\\msys64\\mingw64\\bin\\aqt', 'install', '5.12.9', 'windows', 'desktop', 'win64_mingw73']` Host: `uname_result(system='Windows', node='DESKTOP-GLQ5UIR', release='10', version='10.0.19041', machine='AMD64')`
===========================PLEASE FILE A BUG REPORT===========================
You have discovered a bug in aqt.
Please file a bug report at https://github.com/miurahr/aqtinstall/issues.
Please remember to include a copy of this program's output in your report.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python3.9/multiprocessing/connection.py", line 317, in _recv_bytes

**Comment by ddalcino** [comment]
Thank you for sending this, @dwheeld! I have a couple of follow-up questions:

1. Is this `aqt` version 2.0.0? The "Please file a bug report" message is new, as of one of the 2.0.0 release candidates.
2. If you try a second time, do you get the same error message?
3. `MemoryError` typically only happens when you're running out of memory. Does the problem go away if you shut down programs in the background that you aren't using? How much physical memory/swap space do you have available?
4. This occurred during a phase where the program was concurrently downloading, decompressing, and writing N files at once, where N is determined by the `concurrency` setting in the [`aqt/settings.ini` file](https://aqtinstall.readthedocs.io/en/stable/configuration.html?highlight=config#configuration). By default, N is set to 4; I imagine that if `aqt` was downloading 4 large files at once, it could use up more memory than you have available. Does it work if you reduce N?

**Comment by ddalcino** [comment]
I have some follow-up observations that could help to guide further development:

1. In `aqt/installer.installer`, we use a `try ... except` block to catch `subprocess.CalledProcessError`, but only if the decompression program is not `py7zr`. We could add one that catches exceptions raised by `py7zr`; `MemoryError` would be worthwhile to catch, among others. I think it could be useful to use these `try ... except` blocks to package the name of the compressed file into the `ArchiveExtractionError`; that way, we know which files are causing problems. If there are bugs in `py7zr`, I'm sure that information would be helpful.
2. If we are catching `MemoryError`, and `Settings.concurrency` is > 1, maybe we can automatically suggest that users turn down their concurrency settings.
3. While attempting to recreate this bug locally, I ran into a *LOT* of checksum errors. When it did this, I got a "broken pipe" `OSError` that bypassed the "PLEASE FILE A BUG REPORT" message, probably because of the multithreading. Maybe I'm just having a 'bad network' day. I found it completely impossible to install any version of Qt at all without modifying the code to allow retries when there is a checksum error; some files required 5 retries. I can file a PR that includes my changes, but I'm not sure I'm doing retries properly. `aqt.helper.downloadBinaryFile` is already doing retries on bad connections; my approach just re-runs `aqt.helper.downloadBinaryFile` when there's a checksum error.

**Comment by dwheeld** [comment]
I reinstalled using the instructions from this page and didn't get any error messages:
Build Instructions under Windows 10 (MSYS2) · EdgeTX/edgetx Wiki


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build Instructions under Windows 10 (MSYS2) · EdgeTX/edgetx Wiki

EdgeTX is the cutting edge of OpenTx. Contribute to EdgeTX/edgetx development by creating an account on GitHub.
 |

 |

 |


Everything seemed to work normally until I got to Step 4 - Creating an installer. I then got errors as seen at the end of the list below:

***@***.*** MINGW64 ~/edgetx
$ dir
edgetx_main  edgetx_main-cmake-options.txt

***@***.*** MINGW64 ~/edgetx
$ cd edgetx_main

***@***.*** MINGW64 ~/edgetx/edgetx_main
$ dir
CMakeLists.txt  LICENSE    build-output  companion  radio
GPLv2.txt       README.md  cmake         fw.json    tools

***@***.*** MINGW64 ~/edgetx/edgetx_main
$ cd build-output

***@***.*** MINGW64 ~/edgetx/edgetx_main/build-output
$ make installer
Building Windows NSIS installer...
[  0%] Built target truetype_font_64
[  0%] Built target truetype_font_15
[  0%] Built target truetype_font_16en
[  0%] Built target truetype_font_17en
[  0%] Built target truetype_font_bold17
[  0%] Built target truetype_font_9
[  0%] Built target truetype_font_13
[  0%] Built target truetype_font_16
[  0%] Built target truetype_font_bold16
[  0%] Built target truetype_font_17
[  0%] Built target truetype_font_32
[  0%] Built target truetype_font_24
[  0%] Built target truetype_fonts
[  1%] Built target radio_translations
[  3%] Built target x10_layouts_masks
[  3%] Built target x10_calibration_bitmaps
[  5%] Built target x10_bootloader_bitmaps
[  5%] Built target x10_button_bitmaps
[  5%] Built target x10_bootloader_icons
[  5%] Built target x10_splash
[  5%] Built target x10_alpha_bitmaps
[ 15%] Built target x10_themes_masks
[ 15%] Built target x10_fonts
[ 15%] Built target x10_alpha_calibration_bitmaps
[ 21%] Built target x10_masks
[ 21%] Built target x10_slider_masks
[ 22%] Built target x10_volume_masks
[ 22%] Built target x10_themes_alpha
[ 22%] Built target x10_bitmaps
[ 22%] Built target lua_export_t16
[ 50%] Built target opentx-tx16s-simulator
[ 50%] Built target maxLibQtWidgets
[ 52%] Built target storage
[ 63%] Built target simulation
[ 66%] Built target firmwares
[ 66%] Built target datamodels
[ 70%] Built target common
[ 71%] Built target simulator
[ 77%] Built target shared
[ 85%] Built target modeledit
[ 87%] Built target generaledit
[ 87%] Built target qcustomplot
[100%] Built target companion
Install the project...
-- Install configuration: "Release"
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/companion.exe
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/simulator.exe
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/libopentx-tx16s-simulator.dll
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/dfu-util.exe
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/libusb0.dll
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/libusb-1.0.dll
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/license.txt
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/SDL.dll
Warning: Unable to read c:\Users\qt\work\install\mkspecs\qconfig.pri: The system cannot find the path specified.
Unable to find dependent libraries of c:\Users\qt\work\install\bin\Qt5Core.dll :Cannot open 'c:/Users/qt/work/install/bin/Qt5Core.dll': The system cannot find the path specified.

make[3]: *** [companion/src/CMakeFiles/installer.dir/build.make:72: companion/src/CMakeFiles/installer] Error 1
make[2]: *** [CMakeFiles/Makefile2:2231: companion/src/CMakeFiles/installer.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2238: companion/src/CMakeFiles/installer.dir/rule] Error 2
make: *** [Makefile:1034: installer] Error 2

***@***.*** MINGW64 ~/edgetx/edgetx_main/build-output
$
Any suggestions?



    On Friday, October 1, 2021, 01:49:22 PM CDT, David Dalcino ***@***.***> wrote:  
 
 


I have some follow-up observations that could help to guide further development:
   
   - In aqt/installer.installer, we use a try ... except block to catch subprocess.CalledProcessError, but only if the decompression program is not py7zr. We could add one that catches exceptions raised by py7zr; MemoryError would be worthwhile to catch, among others. I think it could be useful to use these try ... except blocks to package the name of the compressed file into the ArchiveExtractionError; that way, we know which files are causing problems. If there are bugs in py7zr, I'm sure that information would be helpful.
   - If we are catching MemoryError, and Settings.concurrency is > 1, maybe we can automatically suggest that users turn down their concurrency settings.
   - While attempting to recreate this bug locally, I ran into a LOT of checksum errors. When it did this, I got a "broken pipe" OSError that bypassed the "PLEASE FILE A BUG REPORT" message, probably because of the multithreading. Maybe I'm just having a 'bad network' day. I found it completely impossible to install any version of Qt at all without modifying the code to allow retries when there is a checksum error; some files required 5 retries. I can file a PR that includes my changes, but I'm not sure I'm doing retries properly. aqt.helper.downloadBinaryFile is already doing retries on bad connections; my approach just re-runs aqt.helper.downloadBinaryFile when there's a checksum error.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pzhlkj6612** [comment]
Oh, the format of the reply is not good. I'm trying to filter out some useful information.

<br>

@dwheeld wanted to build [EdgeTX/edgetx](https://github.com/EdgeTX/edgetx). According to the documentation ([Build Instructions under Windows 10 (MSYS2)@`d35eff8`](https://github.com/EdgeTX/edgetx/wiki/Build-Instructions-under-Windows-10-(MSYS2)/d35eff8f9c0599963235425020d5037a298f8c0d) ), this project needs a Qt environment that is installed by aqtinstall:

> ### [Prepare the MSYS2 MinGW build environment for EdgeTX](https://github.com/EdgeTX/edgetx/wiki/Build-Instructions-under-Windows-10-(MSYS2)/d35eff8f9c0599963235425020d5037a298f8c0d#prepare-the-msys2-mingw-build-environment-for-edgetx)
> 
> ...
> 
> Install required Python packages using pip. Enter:
> 
> ```
> pip install pillow clang aqtinstall
> ```
> 
> After the installation finishes, issue:
> 
> ```
> aqt install 5.12.9 windows desktop win64_mingw73
> ```
> 
> Wait for the installation to finish. Close the terminal with Ctrl+D again. This concludes the build setup preparations.

And the step 4 is:

> ### [Building Windows programs](https://github.com/EdgeTX/edgetx/wiki/Build-Instructions-under-Windows-10-(MSYS2)/d35eff8f9c0599963235425020d5037a298f8c0d#building-windows-programs)
> 
> ...
> 
> #### [Step 4 - Creating an installer](https://github.com/EdgeTX/edgetx/wiki/Build-Instructions-under-Windows-10-(MSYS2)/d35eff8f9c0599963235425020d5037a298f8c0d#step-4---creating-an-installer)
> 
> To create an installer, issue:
> 
> ```
> make installer
> ```
> 
> This creates under build directory `companion` subfolder binary `companion-windows-2.6.0.exe`. Thus, in `C:\msys64\home\<username>\edgetx\edgetx_main\build-output\companion`, an installer that you can use to install EdgeTX Companion on your system.

However, @dwheeld got a warning and an error related to Qt when executing `make installer` :

```console
$ make installer
Building Windows NSIS installer...
...
... building things
...
Install the project...
-- Install configuration: "Release"
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/companion.exe
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/simulator.exe
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/libopentx-tx16s-simulator.dll
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/dfu-util.exe
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/libusb0.dll
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/libusb-1.0.dll
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/license.txt
-- Up-to-date: C:/msys64/home/d_w_h/edgetx/edgetx_main/build-output/Release/SDL.dll
Warning: Unable to read c:\Users\qt\work\install\mkspecs\qconfig.pri: The system cannot find the path specified.
Unable to find dependent libraries of c:\Users\qt\work\install\bin\Qt5Core.dll :Cannot open 'c:/Users/qt/work/install/bin/Qt5Core.dll': The system cannot find the path specified.

make[3]: *** [companion/src/CMakeFiles/installer.dir/build.make:72: companion/src/CMakeFiles/installer] Error 1
make[2]: *** [CMakeFiles/Makefile2:2231: companion/src/CMakeFiles/installer.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:2238: companion/src/CMakeFiles/installer.dir/rule] Error 2
make: *** [Makefile:1034: installer] Error 2
```

**Comment by pzhlkj6612** [comment]
After googling the path "c:\Users\qt\work\install...", I know that the warning and the error were reported by "windeployqt.exe" when executing [/companion/src/CMakeLists.txt#L446](https://github.com/EdgeTX/edgetx/blob/78489a69c085d4842c7db569ce155f49a76c8e3e/companion/src/CMakeLists.txt#L446). I *guess* this may be caused by a corrupted Qt installation or a wrong environment.

References:

- [Problems with windeployqt after installing 5.11.1 | Qt Forum](https://forum.qt.io/topic/93278)
- [c++ - Copying Qt dlls in post build event using windeployqt is not working - Stack Overflow](https://stackoverflow.com/q/64117288)

**Comment by ddalcino** [comment]
> > After the installation finishes, issue:
> > ```
> > aqt install 5.12.9 windows desktop win64_mingw73
> > ```

One potential issue here is the location to which aqt installed Qt. This command will install Qt to `./5.12.9`, where `.` is the current working directory. You can change the path to which aqt will install Qt with the `--outputdir` flag, but it will always install to a directory with the version number in the name.

> ```console
> Warning: Unable to read c:\Users\qt\work\install\mkspecs\qconfig.pri: The system cannot find the path specified.
> Unable to find dependent libraries of c:\Users\qt\work\install\bin\Qt5Core.dll :Cannot open 'c:/Users/qt/work/install/bin/Qt5Core.dll': The system cannot find the path specified.
> ```

I am unclear as to why the install script/windeployqt is looking for files in `c:\Users\qt\work\install\`; `aqt` will never install to this path. In `aqt/updater.py`, the `Updater` patches several binary files: on Windows, it updates paths that look like `/Users/qt/work/install/*` to point to the correct install path. The path `c:\Users\qt\work\install\mkspecs\qconfig.pri` looks unpatched to me. Maybe we need to audit the paths that `Updater` is patching and make sure that we are patching them all; `grep` could be useful here.

IIRC, the paths that we patch with `Updater` are fallback paths that are only used when certain environment variables are unavailable; I think that `QTDIR` is one of these. If your current working directory was `C:\some_directory` when you installed Qt, then I think `QTDIR` should point to `C:\some_directory\5.12.9\win64_mingw73`. You may be able to avoid all this trouble by setting the `QTDIR` environment variable before running `make installer`.

**Comment by miurahr** [comment]
`c:\Users\qt\work\install\` is a default path embedded in binaries on windows.
aqt updater don't touch windeployqt.exe, so there is a possible fix to update the windeployqt binary.

**Comment by ddalcino** [comment]
> 3. While attempting to recreate this bug locally, I ran into a _LOT_ of checksum errors. ... Maybe I'm just having a 'bad network' day.

Today, when I tried downloading any version of Qt, >95% of all downloads I attempted would result in a checksum error. I think this is related to my VPN; after I disabled it, most downloads would complete successfully again. We should keep this in mind the next time anyone has trouble with checksum errors.

Also, I tried this:

```console
> # from cmd.exe
> python -m aqt install-qt --outputdir D:\Qt windows desktop 5.12.11 win64_mingw73
$ # from WSL
$ grep -a -r -l "/Users/qt/work/install" /mnt/d/Qt/5.12.11    # print a list of all files with "/Users/qt/work/install" in the binary
5.12.11/mingw73_64/bin/Qt53DAnimationd.dll
5.12.11/mingw73_64/bin/Qt53DCored.dll
5.12.11/mingw73_64/bin/Qt53DExtrasd.dll
...   # too much output to comfortably copy here
$ grep -a -r -l "/Users/qt/work/install" /mnt/d/Qt/5.12.11 | wc
    206     206   11094
$ grep -a -r -l "c:/Users/qt/work/install" /mnt/d/Qt/5.12.11 | wc
    206     206   11094
```

That's 206 unique files within which `grep` has located the ASCII string "c:/Users/qt/work/install": the full output is here: https://gist.github.com/ddalcino/791bdfc7c0727df89172740a86828675. Many of these strings don't have any extra space after the string literal, so you would not be able to patch them with a longer path name, the way we can with `qtconfig.pri`. `windeployqt.exe` is not on the list of filenames that include this string, so `windeployqt` must be pulling that string from one of the unpatched files.

I don't think it makes sense to try to patch all 206 files here; that number will be different for each Qt release, and I bet it would be different depending on modules installed. I think it would be more useful to figure out what environment variables need to be set so that these unpatched paths don't need to be accessed, and then make sure people are aware that these variables need to be set.

I also tried grepping for this string on an old install of 5.12.10 I had installed in April, via the official Qt installer. This install contains the "c:/Users/qt/work/install" in many of the same files. I think that this is further evidence that patching these paths is unnecessary, when the right ENV variables are set.

**Comment by ddalcino** [comment]
![image](https://user-images.githubusercontent.com/6743441/135778085-03d1ca3c-d732-476c-a5f9-7bdd5d850a66.png)

Oops, #420 definitely does not fix this issue; I'm not sure why Github thinks it will. Is there any way to remove that tag so we don't close this issue by mistake, if #420 is merged?

**Comment by pzhlkj6612** [comment]
> Oops, #420 definitely does not fix this issue; I'm not sure why Github thinks it will.

I guess it is caused by the [`fixed`](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) keyword in the sentence `Even after I fixed [the issue with my VPN](https://github.com/miurahr/aqtinstall/issues/416#issuecomment-933031438)` .

> Is there any way to remove that tag so we don't close this issue by mistake, if #420 is merged?

Is there a gear in #420 ? Maybe @miurahr has permission to do this.

![Linked issues in the right sidebar](https://docs.github.com/assets/images/help/pull_requests/linked-issues.png)

*The above image is from [Manually linking a pull request to an issue § Linking a pull request to an issue - GitHub Docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue).*

**Comment by miurahr** [comment]
> Is there a gear in #420 ? Maybe @miurahr has permission to do this.

It seems no interface to **remove** link, it may be able to change.

**Comment by pzhlkj6612** [comment]
> It seems no interface to **remove** link, it may be able to **change**.

You're right; we may have to re-open this after merging...

**Comment by ddalcino** [comment]
> > Oops, #420 definitely does not fix this issue; I'm not sure why Github thinks it will.
> 
> I guess it is caused by the [`fixed`](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) keyword in the sentence `Even after I fixed [the issue with my VPN](https://github.com/miurahr/aqtinstall/issues/416#issuecomment-933031438)` .

Good observation; I changed the language and now the link is gone. Thanks!

**Comment by pzhlkj6612** [comment]
> I changed the language and now the link is gone.

Well, yes, it is already documented 🤦‍♂️ :

> ## [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
> 
> Only manually linked pull requests can be manually unlinked. To unlink an issue that you linked using a keyword, you must edit the pull request description to remove the keyword.
