### ISSUE TITLE
Problems with aqt on Windows

### ISSUE THREAD

**Issue by bitbacchus** [miurahr/aqtinstall#423]
First thanks so much for your work! It might save my C++ course this semester for which I have to install Qt Creator in our computer lab.

I ran, however, into some issues on Win 10:

* `pip install aqtinstall` installed version 1.1.4 on Windows (Linux worked fine and installed v 2.0.0). Is there a way to install v 2.0.0 with pip on Windows?
* I tried to use the `aqt.exe` from the repo's release page, but Windows complaint about malicious behaviour and also on virustotal.com finds four security vendors who flag the file as malicious: https://www.virustotal.com/gui/file/b91c8c3aeac8fb22d5127012dee8793d5e40c15da77880448f309ab33d2f09ca/detection 
Any idea why this might be?

Best,
Sebastian

**Comment by ddalcino** [comment]
I am a little out of my depth here, so perhaps someone can correct me if I'm wrong:

1. `aqtinstall` uses `py7zr` to extract `.7z` archive files. There is a command line option to use an alternate extractor utility, like 7zip, but there is no option to install `aqtinstall` without also installing `py7zr`.
2. `py7zr` has a dependency called `bcj-cffi`, which includes helper utilities written in C. Note the "cffi", or "C Foreign Function Interface" in the name. In order to install this dependency, it needs to compile those utilities with a C compiler. I am not sure why pip is looking for MSVC 14 in your case. I suspect that if pip was able to find a working compiler, it would not have this problem.
3. It looks like pip is attempting to install older versions of `aqt`, in an attempt to find one that has a set of dependencies that it can satisfy. I speculate version 1.1.4 requires an older version of `py7zr` that doesn't use the C foreign function interface, and that's why it chose that particular version.

I can think of a couple of potential ways to fix this:

1. Just install Visual Studio. If you're developing native software on Windows, it's very likely that you'll need to install this at some point anyway. I expect that you can just install the most recent version. You might need to run `pip install aqtinstall` from the Visual Studio command line prompt; it will show up in the Start Menu folder for Visual Studio. Fair warning: this will consume a lot of hard disk space, in addition to the Qt installation.
2. Try using `pip install aqtinstall` from within [MSys2](https://www.msys2.org/). MSys is a popular command line environment for Windows that works a lot like Linux. It uses pacman for package management, and it makes it really easy to install modern versions of GCC and mingw. I expect that pip would be able to find a C compiler very easily in this environment. Fair warning: this will also consume a lot of hard disk space.
3. Use `aqt.exe` instead. `aqt.exe` is specifically intended for use in situations like yours, where dependency management is really difficult. Both of the previous options will consume a lot of hard disk space; this one should not.

**Comment by miurahr** [comment]
>py7zr has a dependency called bcj-cffi, which includes helper utilities written in C. Note the "cffi", or "C Foreign Function Interface" in the name. In order to install this dependency, it needs to compile those utilities with a C compiler. I am not sure why pip is looking for MSVC 14 in your case. I suspect that if pip was able to find a working compiler, it would not have this problem.

Now just started a new project [PyBCJ](https://github.com/miurahr/pybcj) that provide a native CPython extension, as same manner as PyPPMd and PyZSTD does, that are helper libraries py7zr depends.
PyPPMd provide native extension library DLL binary for Windows, and also for Linux, macOS, M1 mac and ARM linux.
It will solve your problem, requirements for MSVC,  in future.

**Comment by bitbacchus** [comment]
@pzhlkj6612 
It's a fairly fresh install on a Windows 10 VM, I use `Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]` and `pip 21.2.4 from C:\Users\bacchus\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)` 

@ddalcino 
Thanks for that great summary of all options, that helps a lot. I think I'll give `aqt.exe` another try.

Thank you all for your help! I guess this issue is solved for me and I'll close this :-)

**Comment by pzhlkj6612** [comment]
> Dependencies of aqtinstall may not provide binary extensions for 3.10, at least projects I maintained. Could you downgrade python to 3.9.x, then behavior may be changed.

Oh, haha. I tested with Python 3.9.7 and pip 21.2.3 (installed by the [installer](https://www.python.org/ftp/python/3.9.7/python-3.9.7-amd64.exe) downloaded from python.org) and everything works fine. aqtinstall 2.0.0 has been installed.

**Comment by bitbacchus** [comment]
> Oh, haha. I tested with Python 3.9.7 and pip 21.2.3 (installed by the installer downloaded from python.org) and everything works fine. aqtinstall 2.0.0 has been installed.

Yes, same here! With 3.9.7 everything installs fine!
