### ISSUE TITLE
Unable to download windows mingw binaries on Linux host

### ISSUE THREAD

**Issue by rshamsnejad** [miurahr/aqtinstall#449]
Hello,

I am trying to setup a Docker container to cross-compile Windows binaries on a Linux host using the MinGW toolchain. Here is my Dockerfile so far :

```dockerfile
FROM --platform=linux/amd64 debian:buster

RUN apt-get update

RUN apt-get install -y python3-pip

RUN pip3 install aqtinstall

RUN aqt install-qt windows desktop 5.15.2 win64_mingw81 --outputdir /opt/qt --archives qtbase
```

The aqt step fails with the following error : 

```
aqtinstall(aqt) v2.0.2 on Python 3.7.3 [CPython GCC 8.3.0]
Downloading qtbase...
Redirected: ftp2.nluug.nl
Finished installation of qtbase-Windows-Windows_10-Mingw-Windows-Windows_10-X86_64.7z in 44.70309867
Updater caused an IO error: [Errno 13] Permission denied: '/opt/qt/5.15.2/mingw81_64/bin/qmake.exe'
The command '/bin/sh -c aqt install-qt windows desktop 5.15.2 win64_mingw81 --outputdir /opt/qt --archives qtbase' returned a non-zero code: 1
```

It looks like aqt is trying to execute `/opt/qt/5.15.2/mingw81_64/bin/qmake.exe`, which indeed doesn't have execute permission, and which can't execute anyway since we're on a Linux host.

Am I doing something wrong ? Why is aqt trying to execute qmake ?

Thanks.

**Comment by ddalcino** [comment]
Thank you for opening this issue. This is something that has been bothering me for a while as well. I have noticed that `aqt install-qt` does not work properly when you use it to install Qt for a platform other than the platform that you are on. I had assumed that there was no viable use case for a cross-platform Qt installation, and that's why `aqt` doesn't support it. Your use case proves me wrong.

The relevant code is here:
https://github.com/miurahr/aqtinstall/blob/e25177585dfc3b316f2019336c6bad7779c2a42d/aqt/updater.py#L81-L84
This function is attempting to run [`qmake -query`](https://doc.qt.io/qt-5/qmake-environment-reference.html), which retrieves a list of built-in properties. This list is stored in the `Updater.qconfigs` dictionary, but it doesn't look like it's actually being used anywhere. To me, it looks like it's part of an unfinished feature.

I think that in the case of a cross-platform installation, this function is intended to return False, rather than raise an exception. If that is the case, I propose this change to the above code:

```diff
# aqtinstall/aqt/updater.py, Lines 81 to 84
            try:
                result = subprocess.run([str(qmake_path), "-query"], stdout=subprocess.PIPE)
-            except subprocess.SubprocessError:
+            except (subprocess.SubprocessError, IOError, OSError):
                return False
```

Here, I am catching `IOError` and `OSError`. Windows raises `OSError` when you try to run a binary for another platform, and Linux appears to raise `IOError`. IIRC, Mac raises one of these as well, but I don't remember which.

It might be acceptable to simply catch `Exception` here; I prefer to avoid that as much as possible though.

You could make the case that we need to add CI tests for this; that means adding tests for every cross-platform combination: 6 new tests by my count. I suspect that this could be a waste of CI time though. I will wait for input from @miurahr before I implement any tests.

**Comment by ddalcino** [comment]
@rshamsnejad, does #450 fix the problem for you?

**Comment by rshamsnejad** [comment]
> @rshamsnejad, does #450 fix the problem for you?

Yes it does : 

```shell
root@e61faa89e496:/usr/local/lib/python3.7/dist-packages/aqt# aqt install-qt windows desktop 5.15.2 win64_mingw81 --outputdir /opt/qt --archives qtbase                                                            
aqtinstall(aqt) v2.0.2 on Python 3.7.3 [CPython GCC 8.3.0]                                                                                                                                                         
Downloading qtbase...                                                                                                                                                                                              
Redirected: ftp2.nluug.nl                                                                                                                                                                                          
Finished installation of qtbase-Windows-Windows_10-Mingw-Windows-Windows_10-X86_64.7z in 19.15811919                                                                                                               
Updater caused an IO error: [Errno 13] Permission denied: '/opt/qt/5.15.2/mingw81_64/bin/qmake.exe'                                                                                                                
root@e61faa89e496:/usr/local/lib/python3.7/dist-packages/aqt# vim updater.py 
root@e61faa89e496:/usr/local/lib/python3.7/dist-packages/aqt# aqt install-qt windows desktop 5.15.2 win64_mingw81 --outputdir /opt/qt --archives qtbase
aqtinstall(aqt) v2.0.2 on Python 3.7.3 [CPython GCC 8.3.0]
Downloading qtbase...
Redirected: ftp2.nluug.nl
Finished installation of qtbase-Windows-Windows_10-Mingw-Windows-Windows_10-X86_64.7z in 18.99169890
Finished installation
Time elapsed: 19.96843770 second
```

I modified it by hand for now. I hope it gets merged soon !

Thank you !

**Comment by miurahr** [comment]
I don't think we need tests for cross platform installation.
#450 is enough.
