### ISSUE TITLE
Feature: Try multiple fallbacks on failure

### ISSUE THREAD

**Issue by ann0see** [miurahr/aqtinstall#488]
**Is your feature request related to a problem? Please describe.**
Sometimes our CI fails due to download failures from Qt mirrors. Until yesterday, we didn't know aqt already polls multiple mirrors. Strangely enough this is not always sufficient to have a successful download if multiple mirrors are down. 

**Describe the solution you'd like**
Automatically try 3 or more mirrors before failing.
What does the code actually do at the moment? I thought it already tries multiple mirrors.

**Describe alternatives you've considered**
* Add a ci option to specify the number of mirrors being checked before aqt fails.
* Handle download failures outside of aqt (that's what we're trying at the moment).

**Additional context**
See my PR on our repo: https://github.com/jamulussoftware/jamulus/pull/2333 which is supposed to work around download failures and https://github.com/jamulussoftware/jamulus/runs/5040398208?check_suite_focus=true, https://github.com/jamulussoftware/jamulus/runs/5038967837?check_suite_focus=true
https://github.com/jamulussoftware/jamulus/runs/4966741224?check_suite_focus=true

https://github.com/jamulussoftware/jamulus/runs/4857453378?check_suite_focus=true (seems unrelated)

**Comment by ann0see** [comment]
@hoffie after looking at the code I think it should try multiple mirrors already...

**Comment by hoffie** [comment]
Hm, do you have a pointer? I thought it would try only a single fallback and I thought this was the issue.
https://github.com/miurahr/aqtinstall/blob/eaf5a46e488b69ec1503ca0695020bd7f084ae66/aqt/installer.py#L920

**Comment by ann0see** [comment]
Maybe it's about some master mirror failing?

**Comment by ddalcino** [comment]
This particular failure:
> https://github.com/jamulussoftware/jamulus/runs/4857453378?check_suite_focus=true (seems unrelated)

... actually failed right here: https://github.com/jamulussoftware/jamulus/runs/4857453378?check_suite_focus=true#step:4:148. I don't know why the nonzero return code didn't stop that script, but I am sure that this is the same issue as the other failures you linked to.

The failures you are having are all occurring when aqtinstall is trying to download a `.sha1` file. The code that downloads this file is right here:
https://github.com/miurahr/aqtinstall/blob/cb7eaeeb2afb755a3020ad510b74e62647b3ab99/aqt/installer.py#L1024
The `getUrl` function is supposed to retry downloads `Settings.max_retries_on_connection_error` times; you can change this value in [`aqt/settings.ini`](https://aqtinstall.readthedocs.io/en/latest/configuration.html). The default is 5 attempts. You can try setting it higher, but I am surprised that 5 was not enough.

We last modified this code in #420; it's very possible that the changes do not work.

It's possible that we need to add a CLI option to make `max_retries_on_connection_error` easier to modify.

For now, you can set which `settings.ini` file to use with the `-c` or `--config` option, or by setting the `AQT_CONFIG` environment variable. For the record, I am surprised that there's no mention of `--config` in the CLI options documentation; I'll file a PR to fix this.

**Comment by ann0see** [comment]
Interesting observation. At the moment, the CI works, but still: 5 retries should be enough. I'd assume that even 10 would not have solved the issue in this case. Something else was wrong at that time (but I doubt we can reproduce that).

> I don't know why the nonzero return code didn't stop that script, but I am sure that this is the same issue as the other failures you linked to.

Probably that's an issue in our build script @hoffie ?

**Comment by ddalcino** [comment]
> Concerning the retry logic: How far did you simulate failures? Maybe you could test it by redirecting Qt mirrors to localhost via a hosts file and only allow one mirror.

That stuff is tested with a lot of mocked classes and methods, which could be making incorrect assumptions about how the `requests` library works.

I don't want to test by making requests directly to the actual https://download.qt.io site; it would be too hard to control variables. I like using localhost though; maybe we could spin up a simple server on localhost that will refuse connections n times, and allow the connection on retry number n+1. This approach would improve testing for downloadBinaryFile too.

**Comment by ddalcino** [comment]
> At the moment, the CI works, but still: 5 retries should be enough.

If there was an unusually large amount of traffic at download.qt.io, 5 might not be enough. I've noticed that at certain times of the day (business hours in the US I think), the server is a lot more likely to refuse connections. I think it's a backpressure mechanism, to relieve pressure on the server. In that case, more connection attempts could make the problem worse.

I strongly recommend that you use some kind of caching step in your CI if you aren't already. That would make your builds faster, and also reduce load on the server.

That particular call to getUrl does not fall back on a randomly selected mirror, the way most of the other calls do. It probably should. Falling back to a mirror should help to relieve pressure on download.qt.io. I'll see if I can write a PR for this first.

**Comment by ann0see** [comment]
We‘ll be implementing caching after our next release is out (tomorrow) – a PR is already mostly done on our side, so that would help for sure. However it’s clearly something aqt should at least try to handle better.

**Comment by ddalcino** [comment]
From the [requests documentation](https://2.python-requests.org/en/master/api/#requests.adapters.HTTPAdapter) that documents the mechanism we are using to retry here:
> **max_retries** – The maximum number of retries each connection should attempt. Note, this applies only to failed DNS lookups, socket connections and connection timeouts, never to requests where data has made it to the server.

Certainly, this kind of retry is worth using, but it does not fit my definition of what an actual retry should be. I would rather not try to write tests for this functionality; that kind of testing should be done on the part of the `requests` developers.

It is possible that we need to add an option to retry a download from the same server in addition to trying multiple mirrors. For instance,
1. Try the download n times from download.qt.io
2. Try the download n times from mirror x
3. Try the download n times from mirror y
4. Give up

I am a little concerned about the effects this could have. I think that if a download fails once, it is because a) there's no file there, or b) there's high server load, and they're using backpressure to reduce the load. In either case, you're increasing congestion on the server unnecessarily. Please feel free to try to change my mind on this; I'm not a server architect.

I think the sensible solution is to allow the user to control how many fallback mirrors to use, and I intend to implement this in a PR.

I am refactoring `tests/test_helper.py` to use the [`responses`](https://pypi.org/project/responses/) library instead of mocks, and in the process of doing so, I am discovering several bugs that went unnoticed. Should be a PR for this soon.

**Comment by hoffie** [comment]
> That particular call to getUrl does not fall back on a randomly selected mirror, the way most of the other calls do.

Could this have a security impact though? To what extent are those mirrors trusted?
Currently, the mirror logic seems to aim at moving traffic away from the primary mirror. Having the checksums solely on download.qt.io makes it possible to have less trusted mirrors as any unwanted modification would be detected by a checksum failure.

I fear that those different goals (resilience against outages vs. security and trust of mirrors) might be hard to cover both at the same time.

Our caching (based on action/cache) has been enabled by now, so it might make any Qt download issues less problematic for us.

**Comment by ddalcino** [comment]
> Could this have a security impact though? To what extent are those mirrors trusted? Currently, the mirror logic seems to aim at moving traffic away from the primary mirror. Having the checksums solely on download.qt.io makes it possible to have less trusted mirrors as any unwanted modification would be detected by a checksum failure.

That's a good point; this is definitely a security issue, and thank you for reminding me.

Maybe it makes sense to only trust one source (https://download.qt.io) for the checksum. This would make it easier to implement resilience: just retry the one source n times and not the mirrors. The checksum files aren't that big, and they can't be that much burden for the server. This is definitely doable.

However, if somebody MITM attacks you, and gives you a bad checksum file that says it's from https://download.qt.io, you will have a serious problem. Thanks to HTTPS, this is not an easy attack to carry out, but it's not impossible. I don't know how to deal  with this properly.

Another approach could be a ["Paxos consensus"](https://en.wikipedia.org/wiki/Paxos_(computer_science)) kind of thing, where you ask for checksums from https://download.qt.io and a bunch of mirrors, and allow them to vote for the ground truth should be. But that's another can of worms, and if implemented badly, it will make security a lot worse.

> I fear that those different goals (resilience against outages vs. security and trust of mirrors) might be hard to cover both at the same time.

Security is more important than resilience, every time.

> Our caching (based on action/cache) has been enabled by now, so it might make any Qt download issues less problematic for us.

:+1:

**Comment by hoffie** [comment]
> However, if somebody MITM attacks you, and gives you a bad checksum file that says it's from https://download.qt.io/, you will have a serious problem. Thanks to HTTPS, this is not an easy attack to carry out, but it's not impossible. I don't know how to deal with this properly.

Security-wise, I think the HTTPS guarantees are sufficient. :)

Depending on the size and number of relevant checksum files it might also be viable to include them as part of aqt in a JSON file or something and only download them from qt.io if they are missing from that file (e.g. because the aqt release is older than the most recent Qt release).

**Comment by ddalcino** [comment]
> Security-wise, I think the HTTPS guarantees are sufficient. :)

Yeah, probably.

> Depending on the size and number of relevant checksum files it might also be viable to include them as part of aqt in a JSON file or something and only download them from qt.io if they are missing from that file (e.g. because the aqt release is older than the most recent Qt release).

We already have a cron job running in CI that polls the xml files on the server; we could probably use it to download the checksums. The checksum files are 40 bytes each. 

There are a whole lot of checksums though. We support 8 combinations of host/target, and windows_x86/desktop alone has almost 200 directories in it, and each of those has a lot of directories and multiple checksums in it. If each directory contains 100 checksums (I know some have more than that), then we could have 8 * 200 * 100 * 40 bytes == 12 MB. I think this is a gross overestimate, but I don't know if we want to pack multiple megabytes of checksums into our pypi package. I can imagine a bunch of other things that could go wrong here.

**Comment by ddalcino** [comment]
We are also figuring out what files to download from `Updates.xml` files that can come from mirrors, and composing urls based on the contents of those files. We download both the binary file and the checksum from the same mirror; this is already a security issue if the mirror is compromised.

How do other package managers handle this problem? We should probably stick to conventional best practices for this kind of security, rather than invent our own.

**Comment by ddalcino** [comment]
A couple of observations:
* We are using SHA-1 hashes to verify successful downloads.
* SHA-1 is not our only option. According to [the details page](https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5152/qt.qt5.5152.win64_msvc2019_64/5.15.2-0-202011130602qtbase-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z.mirrorlist) of a randomly selected archive, there are MD5, SHA-1, and SHA-256 hashes available for many archives. I could not find any archives that were missing these files. You can append `.sha256` to each `.7z` download url, and you get the checksum url.
* SHA-256, SHA-1, and MD5 hashes are also available for every `Updates.xml` file

We can probably trust checksums from download.qt.io, but I don't know if we can trust checksums from any of the mirrors. In any case, we have no excuse not to use SHA-256. Both SHA-1 and MD5 have problems with hash collisions.

Here's what I'd like to do:
1. Always download SHA-256 files from download.qt.io, for both binary files and `Updates.xml` files. On failure, retry some number of times, configurable in the settings.ini file (5 by default). This would be a new number, not `max_retries_on_connection_error`.
2. Download binaries and `Updates.xml` files from mirrors, not download.qt.io. This is meant to give those servers a break, since step 1 will necessarily increase server load. The settings file could be used to configure how many mirrors to try, and possibly what order to try them in. If all the mirrors fail, then you could fall back to download.qt.io.

It might make sense to come up with some automatic way of prioritizing mirrors. There's a project at https://github.com/xolox/python-apt-mirror-updater that sorts apt mirrors based on bandwidth in your geographical location; maybe we could borrow ideas or code from it. For me, [the details page](https://download.qt.io/online/qtsdkrepository/windows_x86/desktop/qt5_5152/qt.qt5.5152.win64_msvc2019_64/5.15.2-0-202011130602qtbase-Windows-Windows_10-MSVC2019-Windows-Windows_10-X86_64.7z.mirrorlist) points out mirrors that are in my country or on my continent; we might be able to use that page to select preferred mirrors automatically. I don't know what it does if there aren't any mirrors on your continent.

**Comment by ddalcino** [comment]
#493 should implement the first change that I have proposed here. I don't know if it's done yet, but all the tests are passing right now. It's a much bigger change than I thought it would be when I proposed it.

The second change, with the preferred list of download mirrors, will take some additional work. I wonder if it's really necessary.

**Comment by hoffie** [comment]
Sounds good!

> How do other package managers handle this problem? We should probably stick to conventional best practices for this kind of security, rather than invent our own.

I thin the situation for many other package managers is rather different: They often control the infrastructure and can decide what to provide. Are all files hosted on trusted infrastructure via `https`-only? That might be sufficient. Are files distributed to semi-trusted infrastructure? Just sign the package with a trusted key and/or provide checksums centrally.

For `aqt` we are left with what qt.io provides, so I guess restricting checksum usage to a trusted set of mirrors is the best way possible.

Though rather dated, this provides an overview over some package managers: https://blog.tidelift.com/the-state-of-package-signing-across-package-managers

**Comment by miurahr** [comment]
#493 has been released as v2.1.0rc versions.
@ann0see Are your cases improved?

**Comment by ann0see** [comment]
Hi @miurahr we're using caching now, so I can't tell if it improved. At least we didn't have failures anymore – but used a workaround. If anything goes wrong again, I'll open a new issue.

**Comment by miurahr** [comment]
Thank you for the feedback @ann0see . I'd like to close here and ask you open new one if anything is happened.
