### ISSUE TITLE
ios: qmake script contains non-resolvable target path for Qt 6.2.x

### ISSUE THREAD

**Issue by hoffie** [miurahr/aqtinstall#503]
**Describe the bug**
Qt 6.2.x (maybe earlier versions as well) seems to have changed regarding the `ios` architecture compared to 5.15.2:
1, `$OUTPUT_DIR/6.2.3/ios/bin/qmake` is no longer independent, instead, the `macos/desktop` architecture has to be installed additionally. That's fine (although a bit unintuitive, but I guess there is not much which can be done about it). Maybe aqt could warn about that or even install the required archive (macos/desktop/qtbase) automatically?
2. It looks like `$OUTPUT_DIR/6.2.3/ios/bin/qmake` is supposed to find the `macos` `desktop` qmake, but currently it doesn't due to path changes.

#289 seems related, but apparently isn't enough to fix this.

**To Reproduce**
1. `python3 -m pip install "aqtinstall==2.0.6"`
2. `python3 -m aqt install-qt --outputdir "/usr/local/opt/qt/" mac ios "6.2.3" --archives qtbase qttools qttranslations`
3. `/usr/local/opt/qt/6.2.3/ios/bin/qmake`

**Expected behavior**
qmake only works when manually creating a symlink from the expected location to the new location like that:
https://github.com/hoffie/jamulus/commit/6c7e4751a1b5461e62e17600e2047919a2ce7f4f#diff-ad84ad4ff36c1685f58e8d153980cb299a85fd0f851681459248564f4d3a9b13R27
Another workaround would be not calling ios/bin/qmake by users, but if this is the advise, then ios/bin/qmake should probably not be there in the first place. :)

aqt should insert the proper path into the `qmake` script.

I believe that this place has to be adjusted with version-specific logic:
https://github.com/miurahr/aqtinstall/blob/1a82a92e4c44b0891b6df03f1f5ff371eff2de50/aqt/updater.py#L176

`clang_64` should be `macos` for Qt 6.2.x.
I may try to submit a PR this evening (but feel free to go ahead if you don't hear from me).

**`aqt` output**
```
/usr/local/opt/qt/6.2.3/ios/bin/qmake: line 7: /usr/local/opt/qt/6.2.3/clang_64/bin/qmake: No such file or directory
```

**Desktop (please complete the following information):**
 - macOS 10.15 with ios target
 - `aqtinstall(aqt) v2.0.6 on Python 3.9.10 [CPython Clang 12.0.0 (clang-1200.0.32.29)]` (Update: 2.1.0rc2 shows the same behavior)

**Additional context**
Of course, I might be missing something; I've just noticed that simply replacing 5.15.2 by 6.2.3 no longer leads to a working `qmake` setup for `ios`.

**Comment by ddalcino** [comment]
I wonder if #332 is relevant here? The [Updates.xml file for Qt 6.2.3 ios](https://download.qt.io/online/qtsdkrepository/mac_x64/ios/qt6_623/Updates.xml) contains this:
```xml
<Dependencies>
qt.tools.qtcreator, qt.qt6.623.clang_64, qt.qt6.623.doc, qt.qt6.623.examples
</Dependencies>
```
Qt 6.2.2 for ios also depends on the equivalent `qt.qt6.622.clang_64`, but it looks like Qt 6.2.1 and below do not.

The equivalent [dependencies for android](https://download.qt.io/online/qtsdkrepository/mac_x64/android/qt6_622_armv7/Updates.xml) do not have anything like this, so maybe this isn't an issue on the android side of things:
```xml
<Dependencies>
qt.tools.qtcreator, qt.qt6.623.doc, qt.qt6.623.examples
</Dependencies>
```

I wonder how the official Qt installer handles this. From what I understand of the xml file, I would expect the official installer to just install the whole `qt.qt6.623.clang_64` package (127 MB compressed, 818 MB decompressed). Since `qtbase` is only a small part of that (21 MB compressed), I am skeptical that a naive "just download all stated dependencies" approach is what we want.

If possible, I would rather leverage the `Updates.xml` files to decide which packages/archives to install (as proposed in #332), as opposed to adding a lot of one-off conditional code that installs package X when you request package Y. However, I think we will need to provide users a way to filter which packages and which archives from the dependency list they actually want.

> `clang_64` should be `macos` for Qt 6.2.x.

Honestly, I'm a little surprised that the `Updater.patch_qmake_script()` method works at all without being told what directory to use. That function looks like it's choosing a directory based on what OS the installation is for, which works fine for linux and mac below Qt 6.1.2. I don't see how it makes any sense on Windows; the `mingw81_64` directory should not exist if you're not installing that particular architecture:

https://github.com/miurahr/aqtinstall/blob/893440cf3c56401fef2b641fd1ca34b190aefd4f/aqt/updater.py#L178-L184

In any case, I think it's time to add some more ios build jobs (perhaps Qt 6.2.2) to the Azure Pipeline script here:
https://github.com/miurahr/aqtinstall/blob/1a82a92e4c44b0891b6df03f1f5ff371eff2de50/ci/generate_azure_pipelines_matrices.py#L271

**Comment by hoffie** [comment]
> If possible, I would rather leverage the Updates.xml files to decide which packages/archives to install (as proposed in https://github.com/miurahr/aqtinstall/issues/332), as opposed to adding a lot of one-off conditional code that installs package X when you request package Y.

Understood. (1) from my issue description is the less-relevant part. It is workaroundable by the user by choosing to install the proper dependencies. It's not optimal, but still clean, IMO.

The broken qmake script (2) is what I think would be good to fix in the sort-term, as custom symlinks do not sound like a clean solution... :)

> Honestly, I'm a little surprised that the Updater.patch_qmake_script() method works at all without being told what directory to use. That function looks like it's choosing a directory based on what OS the installation is for, which works fine for linux and mac below Qt 6.1.2.

Yes, I was wondering as well as I was trying to derive the proper values from other variables, but wasn't able to (especially for Windows). How should we go forward here? I feel confident adding a conditional there and can provide a PR. I don't feel confident reworking that part completely as I lack history, context and knowledge... :)

**Comment by ddalcino** [comment]
> The broken qmake script (2) is what I think would be good to fix in the short-term, as custom symlinks do not sound like a clean solution... :)

Indeed. I think you deserve a very big thank-you for pointing this problem out.

> Yes, I was wondering as well as I was trying to derive the proper values from other variables, but wasn't able to (especially for Windows). How should we go forward here? I feel confident adding a conditional there and can provide a PR. I don't feel confident reworking that part completely as I lack history, context and knowledge... :)

I think we need a centralized, reusable function that returns the folder name for the desktop version of Qt, i.e. `gcc_64` for linux, `clang_64`/`macos` for mac depending on the version, and for now we can stick to the existing `mingw81_64` for windows. `mingw81_64` is undoubtedly not the right choice for all situations; that architecture does not even exist for several versions of Qt. I would prefer an approach that checks what desktop Qts are available and chooses one, but that's a job for another day.

I've started a PR, #510, that adds tests for this. I think the tests are appropriate; you can see a failure to build an iOS project due to an incorrect patch here: https://dev.azure.com/miurahr/github/_build/results?buildId=5074&view=logs&j=1ea727ed-2050-5877-9d96-adddb35f7943&t=b67eabc5-7e7e-54c5-0f88-bc35772ccffe&l=41. The equivalent build for Qt 5.15.2 passes. @hoffie, if you'd like to work on this, please pull my branch at https://github.com/ddalcino/aqtinstall/tree/fix-mac-qmake-patch and see what you can do with `aqt/updater.py`. I will leave #510 as a draft for a week to give you time to work on it, if you'd like. If you aren't interested, I can do it. It should be a pretty quick fix.

Additionally, if you think my tests could use improvement, I'd appreciate the feedback. I don't know if [accelbubble](https://doc.qt.io/qt-6/qtsensors-accelbubble-example.html) is the best example to use for iOS; maybe you know of a better one. I used accelbubble because we're already using it to test Android versions of Qt.

**Comment by ddalcino** [comment]
@hoffie I hope #510 fixed this for you. Can you please let us know if https://github.com/miurahr/aqtinstall/releases/tag/v2.1.0rc4 has solved this for you?

**Comment by hoffie** [comment]
Sorry for responding so late, got caught up with real life stuff.

> @hoffie, if you'd like to work on this, please pull my branch at https://github.com/ddalcino/aqtinstall/tree/fix-mac-qmake-patch and see what you can do with aqt/updater.py. I will leave https://github.com/miurahr/aqtinstall/pull/510 as a draft for a week to give you time to work on it, if you'd like. If you aren't interested, I can do it. It should be a pretty quick fix.

Having looked at the PR now, I don't think I could have done in that way. Thanks for working on this!

> Additionally, if you think my tests could use improvement, I'd appreciate the feedback. I don't know if [accelbubble](https://doc.qt.io/qt-6/qtsensors-accelbubble-example.html) is the best example to use for iOS; maybe you know of a better one. I used accelbubble because we're already using it to test Android versions of Qt.

Sorry, I'm not deeper into iOS or mobile Qt stuff (I don't even own an Apple device ;)).

> I hope https://github.com/miurahr/aqtinstall/pull/510 fixed this for you. Can you please let us know if https://github.com/miurahr/aqtinstall/releases/tag/v2.1.0rc4 has solved this for you?

v2.1.0 works without symlink workarounds. Thanks!
