### ISSUE TITLE
Add a -feature-thread option on WASM installation

### ISSUE THREAD

**Issue by Nydauron** [miurahr/aqtinstall#652]
**Is your feature request related to a problem? Please describe.**
My team and I are currently working on a WASM project that requires the use of pthreads. We also want to integrate Qt into the build to help with GUI drawing. I installed Qt using the following command: `aqt install-qt linux desktop 6.4.2 wasm_32 --autodesktop -O ~/QT`.

Our current configuration finds Qt by using the following cmake command:
```
emcmake ~/QT/6.4.2/wasm_32/bin/qt-cmake -B ./build -DCMAKE_BUILD_TYPE=Release -DQT_HOST_PATH=~/QT/6.4.2/gcc_64 -DCMAKE_PREFIX_PATH=~/QT/6.4.2/wasm_32 -DCMAKE_FIND_ROOT_PATH=~/QT/6.4.2/wasm_32 -DQT_HOST_PATH_CMAKE_DIR=~/QT/6.4.2/gcc_64/lib/cmake
```

However, the compilation fails during linking with the following error: (output from `cmake --build ./build -j`)

```bash
wasm-ld: error: --shared-memory is disallowed by qcolor.cpp.o because it was not compiled with 'atomics' or 'bulk-memory' features.
```

We are currently including `Qt::Core` and `Qt::Gui`. Based on the above error, my assumption is that the current precompiled versions of the WASM targets were not configured with the `-feature-thread` enabled.

**Describe the solution you'd like**
For when the user requests for a wasm target (e.g. `wasm_32`), add the option on installation to install the libraries that were compiled with the `-feature-thread` option configured.

An example command would look like:
```
aqt install-qt linux desktop 6.4.2 wasm_32 --feature-thread --autodesktop -O ~/QT
```

**Describe alternatives you've considered**
Other alternatives would be to compile Qt from source with the `-feature-thread` option, but I haven't had much success with this, and it will complicate our development setup for the rest of my team.

**Comment by ddalcino** [comment]
I could be wrong, but I'm not sure that's going to work with the `wasm_32` architecture. AFAIK it's always going to be single-threaded. Qt 6.5.0 added a `wasm_multithread` architecture, and if I were you I would try that first. We just added support for it in #648, which has not made it to release yet.

Are you able to compile and link successfully using Qt 6.4 with the official installer? If so, then maybe there's a problem here that we can fix. Otherwise, there might not be anything we can do. This project is entirely dependent on the binaries the Qt maintainers release on their website; we aren't building Qt ourselves.

**Comment by Nydauron** [comment]
Thanks for the quick reply!

Yes, using `wasm_multithread` looks like it worked. Thanks again!
