### ISSUE TITLE
debug_info missing

### ISSUE THREAD

**Issue by rectalogic** [miurahr/aqtinstall#719]
**Describe the bug**
`debug_info` archive not available for macOS with 6.6.0

**To Reproduce**
```
$ aqt list-qt mac desktop --archives 6.6.0 clang_64 debug_info
ERROR   : The requested modules were not located: ['debug_info']
==============================Suggested follow-up:==============================
* Please use 'aqt list-qt mac desktop' to show versions of Qt available.
* Please use 'aqt list-qt mac desktop --arch <QT_VERSION>' to show architectures available.
* Please use 'aqt list-qt mac desktop --modules <QT_VERSION>' to show modules available.
*
```
It's there for 6.5.3, and for 6.6.0 linux:
```
$ aqt list-qt mac desktop --archives 6.5.3 clang_64 debug_info
qt3d qt5compat qtbase qtcharts qtcoap qtconnectivity qtdatavis3d qtdeclarative qtgrpc qthttpserver qtimageformats qtlanguageserver qtlocation qtlottie qtmqtt qtmultimedia qtnetworkauth qtopcua qtpositioning qtquick3d qtquick3dphysics qtquickeffectmaker qtquicktimeline qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtshadertools qtspeech qtsvg qttools qtvirtualkeyboard qtwebchannel qtwebengine qtwebsockets qtwebview
```
```
$ aqt list-qt linux desktop --archives 6.6.0 gcc_64 debug_info
qt3d qt5compat qtbase qtcharts qtcoap qtconnectivity qtdatavis3d qtdeclarative qtgraphs qtgrpc qthttpserver qtimageformats qtlanguageserver qtlocation qtlottie qtmqtt qtmultimedia qtnetworkauth qtopcua qtpositioning qtquick3d qtquick3dphysics qtquickeffectmaker qtquicktimeline qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtshadertools qtspeech qtsvg qttools qtvirtualkeyboard qtwayland qtwebchannel qtwebengine qtwebsockets qtwebview
```
**Expected behavior**
Want `debug_info` for macos 6.6.0.
I'm guessing this is not an aqtinstall issue and Qt is just not shipping this any more?

**`aqt` output**
See above

**Desktop (please complete the following information):**
 - OS: macOS 13
 - `INFO    : aqtinstall(aqt) v3.1.7 on Python 3.11.5 [CPython Clang 14.0.3 (clang-1403.0.22.14.1)]`

**Comment by ddalcino** [comment]
> I'm guessing this is not an aqtinstall issue and Qt is just not shipping this any more?

Yes, something like that. This is expected behavior for the Qt maintainers; some modules just go missing in some releases for some platforms, and it's really hard to predict what they're going to do. `aqt list-qt` just reports what's available at https://download.qt.io/online/qtsdkrepository/. 

This is an upstream issue, and not something we have any control over; it's up for the Qt maintainers to provide this module. You are welcome to file a bug report using the directions here: https://wiki.qt.io/Reporting_Bugs

If you want a more predictable experience, I recommend just using an LTS version like 6.5.* for as long as possible.

**Comment by rectalogic** [comment]
Thanks for the insight. I filed https://bugreports.qt.io/browse/QTBUG-118186
